package com.test;

import javax.swing.*;
import java.awt.*;

public class App2 {
    private JPanel panel2;
    private JTable table1;

    public static void main(String[] args) {
        JFrame frame = new JFrame("App2");
        frame.setContentPane(new App2().panel2);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        JMenuBar manuBar = new JMenuBar();
        JMenuItem menuItem = new JMenuItem("Close");
        JMenuItem menuItem2 = new JMenuItem("Add");
        JMenu menu = new JMenu("Program");
        menu.getAccessibleContext().setAccessibleDescription(
                "The only menu in this program that has menu items");
        manuBar.add(menu);
        JMenu menu2 = new JMenu("Work");
        menu2.getAccessibleContext().setAccessibleDescription(
                "The only menu in this program that has menu items");
        manuBar.add(menu2);
        menu2.add(menuItem2);
        menu.add(menuItem);
        frame.setJMenuBar(manuBar);
        }
    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        table1 = new JTable();
        panel2.add(table1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel2;
    }
}
